- isOverflown testen (gedaan, kan alleen met add of mul of sub als functie)
- Zoek precisie uit van Numeric Integration (gedaan, Simpson heeft een precisie van EPS^4 voor een vast interval en EPS^5 voor een interval van lengte EPS)
- Voeg uitleg toe van Fast Hadamard Transform
- Voeg wat standaard primitive roots toe
- Probeer fast subset convolution
- Zoek gnu order tree uit en maak duidelijkere code
- Wat is een cartesian tree?
